- name: install nginx server
  hosts: local 
  become: yes
  connection: local
  tasks:
  - name: install web nginx server
    ansible.builtin.package:
     name: nginx
     state: present

  - name: start mysql
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes   